// Generated by https://quicktype.io

import { IPerson } from './Iowners'

export interface IcontractsResponse {
	results: number
	code: number
	status: string
	ok: boolean
	data: Contract[]
}

export interface Contract {
	id: number
	uuid: string
	PropertyId: number
	ClientId: number
	startDate: string
	endDate: string
	// nroPartWater: string
	// nroPartMuni: string
	// nroPartAPI: string
	// commission: number
	state: string
	description: string
	deposit: number
	booking: number
	// warrantyInquiry: number
	createdAt: string
	updatedAt: string
	Client: Client
	Property: Property
	PriceHistorials: IHistorialPrice[]
	amount: number
}

export interface Client {
	fullName: string
	address: string
	phone: string
	email: string
	cuit: string
}
export interface IHistorialPrice {
	id: number
	ContractId: number
	amount: number
	year: number
	percent: number
	createdAt: string
	updatedAt: string
	deletedAt: null | string
}

export interface Property {
	id: number
	uuid: string
	ZoneId: number
	PropertyTypeId: number
	Owner: IPerson
	OwnerId: number
	street: string
	number: string
	floor: string
	dept: string
	isFor: string
	state: string
	description: string
	createdAt: string
	updatedAt: string
}
