// Generated by https://quicktype.io

export interface IcontractsResponse {
  results: number;
  code: number;
  status: string;
  ok: boolean;
  data: Contract[];
}

export interface Contract {
  id: number;
  uuid: string;
  PropertyId: number;
  ClientId: number;
  startDate: string;
  endDate: string;
  nroPartWater: string;
  nroPartMuni: string;
  nroPartAPI: string;
  commission: number;
  state: string;
  description: string;
  stamped: number;
  fees: number;
  warrantyInquiry: number;
  createdAt: string;
  updatedAt: string;
  Client: Client;
  Property: Property;
  amount: number;
}

export interface Client {
  fullName: string;
  address: string;
  phone: string;
  email: string;
  cuit: string;
}

export interface Property {
  id: number;
  uuid: string;
  ZoneId: number;
  PropertyTypeId: number;
  OwnerId: number;
  street: string;
  number: string;
  floor: string;
  dept: string;
  isFor: string;
  state: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}
