// Generated by https://quicktype.io

export interface IEventualitiesResponse {
  results: number;
  code:    number;
  status:  string;
  ok:      boolean;
  data:    Datum[];
}

export interface Datum {
  id:           number;
  ContractId:   number;
  clientAmount: number;
  ownerAmount:  number;
  clientPaid:   boolean;
  ownerPaid:    boolean;
  description:  string;
  expiredDate:  string;
  createdAt:    string;
  updatedAt:    string;
  deletedAt:    null;
  Contract:     Contract;
}

export interface Contract {
  startDate: string;
  endDate:   string;
  id:        number;
  state:     string;
  Property:  Property;
}

export interface Property {
  street: string;
  number: string;
  floor:  string;
  dept:   string;
  id:     number;
}
