// Generated by https://quicktype.io

export interface IEventualitiesResponse {
	results: number
	code: number
	status: string
	ok: boolean
	data: IEventuality[]
}

export interface IEventuality {
	id: number
	ContractId: number
	clientAmount: number
	ownerAmount: number
	clientPaid: boolean
	ownerPaid: boolean
	description: string
	expiredDate: string
	createdAt: string
	updatedAt: string
	deletedAt: null
}
