// Generated by https://quicktype.io

export interface IownersResponse {
  results: number;
  code: number;
  status: string;
  ok: boolean;
  data: IPerson[];
}

export interface IPerson {
  id: number;
  uuid: string;
  fullName: string;
  address: string;
  phone: string;
  email: string;
  cuit: string;
  nroFax: string;
  province: string;
  city: string;
  obs: string;
  createdAt: string;
  updatedAt: string;
}
