// Generated by https://quicktype.io

export interface IpaymentTypeResponse {
  code: number;
  success: boolean;
  message: string;
  data: IpaymentType[];
}

export interface IpaymentType {
  id: number;
  uuid: string;
  name: string;
  createdAt?: string;
  updatedAt?: string;
}
