// Generated by https://quicktype.io

export interface IzonesResponse {
  code: number;
  success: boolean;
  message: string;
  data: Izone[];
}

export interface Izone {
  id: number;
  uuid: string;
  name: string;
  createdAt?: string;
  updatedAt?: string;
}
