// TODO:: LAST TEST WITH INTERFACES AND AVERYTHING WORKING
// TODO:: DOWNLOAD PAYMENT RECEIPT FOR CLIENT AND PROPERTY
// TODO:: DEBTS PROPERTY AND STRUCTURE THE DETAILS PREVIEW

// TODO:: menus and submenus on mobile
// TODO :FORMAT NUMBER TO CURRENCY WITH TWO NUMBER DECIMALS
// TODO :: ADD MONTH AND YEAR TO THE PAYMENT RECEIPT

// TODO :: when revert payment remove eventuality for diferences from paidTotal and total 