// TODO:: LAST TEST WITH INTERFACES AND AVERYTHING WORKING
// TODO:: DOWNLOAD PAYMENT RECEIPT FOR CLIENT AND PROPERTY
// TODO:: DEBTS PROPERTY AND STRUCTURE THE DETAILS PREVIEW

// TODO:: menus and submenus on mobile